CREATE TABLE agencias (
    id CHAR(36) PRIMARY KEY,
    id_user CHAR(36) NOT NULL UNIQUE,
    razao_social VARCHAR(255) UNIQUE,
    nome_fantasia VARCHAR (255),
    username VARCHAR(255) UNIQUE,
    cnpj VARCHAR(18) UNIQUE,
    deleted_at DATE,
    FOREIGN KEY (id_user) REFERENCES users(id)
);

CREATE TABLE paises (
    id CHAR(2) PRIMARY KEY,
    nome VARCHAR(100),
    idioma_principal VARCHAR(30) NOT NULL,
    moeda VARCHAR(30),
    deleted_at DATE
);

CREATE TABLE destinos (
    id CHAR(36) PRIMARY KEY,
    id_agencia CHAR(36) NOT NULL,
    id_pais CHAR(2) NOT NULL,
    cidade VARCHAR(60) NOT NULL,
    universidade VARCHAR(60) NOT NULL,
    descricao TEXT,
    curtidas INT,
    preco DECIMAL(10, 2),
    deleted_at DATE,
    FOREIGN KEY (id_agencia) REFERENCES agencias(id),
    FOREIGN KEY (id_pais) REFERENCES paises(id)
);

INSERT INTO paises (id, nome, idioma_principal, moeda, deleted_at) VALUES
('US', 'Estados Unidos', 'Inglês', 'Dólar', NULL),
('CA', 'Canadá', 'Inglês', 'Dólar Canadense', NULL),
('GB', 'Reino Unido', 'Inglês', 'Libra', NULL),
('IE', 'Irlanda', 'Inglês', 'Euro', NULL),
('AU', 'Austrália', 'Inglês', 'Dólar Australiano', NULL),
('NZ', 'Nova Zelândia', 'Inglês', 'Dólar Neozelandês', NULL),
('FR', 'França', 'Francês', 'Euro', NULL),
('DE', 'Alemanha', 'Alemão', 'Euro', NULL),
('ES', 'Espanha', 'Espanhol', 'Euro', NULL),
('IT', 'Itália', 'Italiano', 'Euro', NULL),
('PT', 'Portugal', 'Português', 'Euro', NULL),
('NL', 'Países Baixos', 'Holandês', 'Euro', NULL),
('BE', 'Bélgica', 'Holandês', 'Euro', NULL),
('CH', 'Suíça', 'Alemão', 'Franco Suíço', NULL),
('AT', 'Áustria', 'Alemão', 'Euro', NULL),
('SE', 'Suécia', 'Sueco', 'Coroa Sueca', NULL),
('NO', 'Noruega', 'Norueguês', 'Coroa Norueguesa', NULL),
('DK', 'Dinamarca', 'Dinamarquês', 'Coroa Dinamarquesa', NULL),
('FI', 'Finlândia', 'Finlandês', 'Euro', NULL),
('PL', 'Polônia', 'Polonês', 'Zloty', NULL),
('CZ', 'República Tcheca', 'Tcheco', 'Coroa Tcheca', NULL),
('HU', 'Hungria', 'Húngaro', 'Forint', NULL),
('GR', 'Grécia', 'Grego', 'Euro', NULL),
('TR', 'Turquia', 'Turco', 'Lira', NULL),
('JP', 'Japão', 'Japonês', 'Iene', NULL),
('KR', 'Coreia do Sul', 'Coreano', 'Won', NULL),
('CN', 'China', 'Mandarim', 'Yuan', NULL),
('IN', 'Índia', 'Hindi', 'Rupia', NULL),
('TH', 'Tailândia', 'Tailandês', 'Baht', NULL),
('SG', 'Singapura', 'Inglês', 'Dólar de Singapura', NULL),
('MY', 'Malásia', 'Malaio', 'Ringgit', NULL),
('ID', 'Indonésia', 'Indonésio', 'Rupia Indonésia', NULL),
('PH', 'Filipinas', 'Inglês', 'Peso Filipino', NULL),
('VN', 'Vietnã', 'Vietnamita', 'Dong', NULL),
('AE', 'Emirados Árabes Unidos', 'Árabe', 'Dirham', NULL),
('IL', 'Israel', 'Hebraico', 'Shekel', NULL),
('SA', 'Arábia Saudita', 'Árabe', 'Rial', NULL),
('ZA', 'África do Sul', 'Inglês', 'Rand', NULL),
('EG', 'Egito', 'Árabe', 'Libra Egípcia', NULL),
('MA', 'Marrocos', 'Árabe', 'Dirham', NULL);

INSERT INTO paises (id, nome, idioma_principal, moeda, deleted_at) VALUES
('BR', 'Brasil', 'Português', 'Real', NULL),
('AR', 'Argentina', 'Espanhol', 'Peso Argentino', NULL),
('CL', 'Chile', 'Espanhol', 'Peso Chileno', NULL),
('CO', 'Colômbia', 'Espanhol', 'Peso Colombiano', NULL),
('MX', 'México', 'Espanhol', 'Peso Mexicano', NULL),
('PE', 'Peru', 'Espanhol', 'Sol', NULL),
('UY', 'Uruguai', 'Espanhol', 'Peso Uruguaio', NULL),
('CR', 'Costa Rica', 'Espanhol', 'Colón', NULL),
('PA', 'Panamá', 'Espanhol', 'Balboa/Dólar', NULL),
('IS', 'Islândia', 'Islandês', 'Coroa Islandesa', NULL),
('LU', 'Luxemburgo', 'Alemão', 'Euro', NULL),
('EE', 'Estônia', 'Estoniano', 'Euro', NULL),
('LV', 'Letônia', 'Letão', 'Euro', NULL),
('LT', 'Lituânia', 'Lituano', 'Euro', NULL),
('SK', 'Eslováquia', 'Eslovaco', 'Euro', NULL),
('SI', 'Eslovênia', 'Esloveno', 'Euro', NULL),
('HR', 'Croácia', 'Croata', 'Euro', NULL),
('BG', 'Bulgária', 'Búlgaro', 'Lev', NULL),
('RO', 'Romênia', 'Romeno', 'Leu', NULL)